name: rick_and_morty_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  animate_do: ^3.0.2
  card_swiper: ^3.0.1
  dio: ^5.3.0
  equatable: ^2.0.5
  firebase_auth: ^4.7.2
  firebase_core: ^2.15.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_dotenv: ^5.1.0
  flutter_keyboard_visibility: ^5.4.1
  flutter_localizations:
    sdk: flutter
  flutter_staggered_grid_view: ^0.6.2
  font_awesome_flutter: ^10.5.0
  formz: ^0.6.0
  go_router: ^9.0.3
  google_fonts: ^5.1.0
  google_sign_in: ^6.1.4
  intl: any
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.0.15
  shared_preferences: ^2.2.0
  youtube_player_flutter: ^8.1.2

dev_dependencies:
  build_runner: ^2.4.6
  change_app_package_name: ^1.1.0
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  isar_generator: ^3.1.0+1

flutter_launcher_icons:
  android: "launcher_icon" # can specify file name here e.g. "ic_launcher"
  ios: true # can specify file name here e.g. "My-Launcher-Icon"
  image_path: "assets/images/launcher_icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter:
  uses-material-design: true
  assets:
    - .env
    - google_fonts/Amatic_SC/
    - assets/certificate/certificate.pem
    - assets/images/
    - assets/i18n/
